from setuptools import setup, find_packages

setup(
    name="resume-relevance-system",
    version="1.0.0",
    description="Automated Resume Relevance Check System",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "flask>=2.3.3",
        "fastapi>=0.104.1",
        "uvicorn>=0.24.0",
        "streamlit>=1.28.1",
        "PyMuPDF>=1.23.8",
        "pdfplumber>=0.10.0",
        "python-docx>=1.1.0",
        "docx2txt>=0.8",
        "spacy>=3.7.2",
        "nltk>=3.8.1",
        "scikit-learn>=1.3.2",
        "fuzzywuzzy>=0.18.0",
        "python-Levenshtein>=0.23.0",
        "langchain>=0.0.340",
        "langchain-openai>=0.0.2",
        "langchain-community>=0.0.10",
        "openai>=1.3.7",
        "google-generativeai>=0.3.2",
        "anthropic>=0.7.8",
        "chromadb>=0.4.18",
        "faiss-cpu>=1.7.4",
        "pinecone-client>=2.2.4",
        "sqlalchemy>=2.0.23",
        "pandas>=2.1.4",
        "numpy>=1.25.2",
        "python-multipart>=0.0.6",
        "python-dotenv>=1.0.0",
        "Pillow>=10.1.0",
        "plotly>=5.17.0",
        "flask-cors>=4.0.0",
        "requests>=2.31.0"
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)